/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rpgo;

import ClassesRpGo.Funcionario;
import ClassesRpGo.Jogador;
import ClassesRpGo.Pessoa;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class InserirJogador extends javax.swing.JFrame {

    boolean flag2 = false;
    
    public InserirJogador() {
        initComponents();
        txtfNome.setText("Nome");
        txtfIdJogador.setText(Integer.toString(Pessoa.ID));
        montarTela();
        getContentPane().setBackground(new java.awt.Color(30, 30, 30));
        setLocationRelativeTo(null);
    }
    public InserirJogador(Jogador jogador) {
        initComponents();
        flag2 = true;
        txtfNome.setText(jogador.getNome());
        txtfIdJogador.setText(Integer.toString(jogador.getId()));
        montarTela();
        getContentPane().setBackground(new java.awt.Color(30, 30, 30));
        setLocationRelativeTo(null);
    }
    private void saveToFile(Jogador jogador) {
        // Caminho do arquivo
        String fileName = "src\\Save\\Jogadores.txt";

        // Convertendo jogador para string e salvando no arquivo
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName, true))) {
            writer.write(jogador.toFileString());
            writer.newLine();
            writer.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private boolean checkIfExists(Jogador jogador) {
        // Caminho do arquivo
        String fileName = "src\\Save\\Jogadores.txt";

        // Verificando se o jogador já existe no arquivo
        try {
            Path path = Paths.get(fileName);
            if (Files.exists(path)) {
                return Files.lines(path).anyMatch(line -> line.contains(jogador.getNome()));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

        return false;
    }
    private void montarTela(){
        txtfNome.setForeground(new java.awt.Color(169, 169, 169));
        txtfNome.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txtfNome.getText().equals("Nome")) {
                txtfNome.setText("");
                txtfNome.setForeground(new java.awt.Color(255, 255, 255));
            }
        }
        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txtfNome.getText().isEmpty()) {
                txtfNome.setForeground(new java.awt.Color(169, 169, 169));
                txtfNome.setText("Nome");
            }
        }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        txtfNome = new javax.swing.JTextField();
        lblRegistroJogador = new javax.swing.JLabel();
        txtDataJogador = new javax.swing.JFormattedTextField();
        txtfIdJogador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Novo Jogador");

        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Data de Nascimento:");

        lblNome.setForeground(new java.awt.Color(242, 242, 242));
        lblNome.setText("Nome");

        lblId.setForeground(new java.awt.Color(242, 242, 242));
        lblId.setText("ID");

        btnSalvar.setBackground(new java.awt.Color(86, 86, 86));
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        txtfNome.setBackground(new java.awt.Color(40, 40, 40));
        txtfNome.setForeground(new java.awt.Color(255, 255, 255));

        lblRegistroJogador.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistroJogador.setForeground(new java.awt.Color(242, 242, 242));
        lblRegistroJogador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegistroJogador.setText("Cadastro de Jogador");

        txtDataJogador.setBackground(new java.awt.Color(40, 40, 40));
        txtDataJogador.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtDataJogador.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataJogadorActionPerformed(evt);
            }
        });

        txtfIdJogador.setEnabled(false);
        txtfIdJogador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfIdJogadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtDataJogador)
                            .addGap(87, 87, 87)
                            .addComponent(btnSalvar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNome))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(txtfIdJogador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(1, 1, 1))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addComponent(lblRegistroJogador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblRegistroJogador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfIdJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(txtDataJogador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataJogadorActionPerformed

    private void txtfIdJogadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfIdJogadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfIdJogadorActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    boolean flag = true;
        
    String nome = txtfNome.getText();
    String dataDeNascimento = txtDataJogador.getText();

    // Criando uma instância de Funcionario
    Jogador jogador = new Jogador(Pessoa.ID, nome, dataDeNascimento);
    // Verificando se o funcionário já existe
    if(txtfNome.getText().equals("Nome")){
        JOptionPane.showMessageDialog(this, "Escreva algo no campo Nome");
        
        flag = false;
    }
    
    if(!checkIfExists(jogador) || flag2 == true) {
        if(flag == true){
            if(flag2 == true){
                    Jogador.removerPessoaDoArquivo(txtfIdJogador.getText(), "src\\Save\\Jogadores.txt", false);
                    
                    jogador.setId(Integer.parseInt(txtfIdJogador.getText()));
                    
                    saveToFile(jogador);
        
                    dispose();
            }
            else{
                    saveToFile(jogador);
        
                    Pessoa.ID += 1;
                    
                    dispose();
            }
        }
    }
    else{
        // Exibir mensagem de que o funcionário já existe
        JOptionPane.showMessageDialog(this, "Jogador já existe!");
        
        dispose();
    }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InserirJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRegistroJogador;
    private javax.swing.JFormattedTextField txtDataJogador;
    private javax.swing.JTextField txtfIdJogador;
    private javax.swing.JTextField txtfNome;
    // End of variables declaration//GEN-END:variables
}
